### ISSUE TITLE
Invalid syntax 

### ISSUE THREAD

**Issue by evildevill** [pri1311/crunch#1]
/home/crunch/website/views.py", line 10
    copy cloud config data here
         ^^^^^
SyntaxError: invalid syntax

**Comment by RichardProchadzka** [comment]
/tmp/flask-chat/crunch/db.sqlite
Traceback (most recent call last):
  File "/tmp/flask-chat/crunch/main.py", line 12, in <module>
    app = create_app()
  File "/tmp/flask-chat/crunch/website/__init__.py", line 112, in create_app
    from .views import views
  File "/tmp/flask-chat/crunch/website/views.py", line 10
    copy cloud config data here
         ^^^^^
SyntaxError: invalid syntax

**Comment by RichardProchadzka** [comment]
funny that you make something for someone and it does not work and if ... there is no support at all :dancers:
