### ISSUE TITLE
error whan try to singup

### ISSUE THREAD

**Issue by sudo-py-dev** [pri1311/crunch#4]
ValueError

ValueError: Must supply api_key
Traceback (most recent call last)

    File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2464, in __call__

    return self.wsgi_app(environ, start_response)

    File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_socketio\__init__.py", line 45, in __call__

    return super(_SocketIOMiddleware, self).__call__(environ,

    File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\engineio\middleware.py", line 74, in __call__

    return self.wsgi_app(environ, start_response)

    File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2450, in wsgi_app

    response = self.handle_exception(e)

    File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1867, in handle_exception

    reraise(exc_type, exc_value, tb)

    File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\_compat.py", line 39, in reraise

    raise value

    File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2447, in wsgi_app

    response = self.full_dispatch_request()

    File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1952, in full_dispatch_request

    rv = self.handle_user_exception(e)

    File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1821, in handle_user_exception

    reraise(exc_type, exc_value, tb)

    File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\_compat.py", line 39, in reraise

    raise value

    File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1950, in full_dispatch_request

    rv = self.dispatch_request()

    File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1936, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

    File "C:\Users\user\OneDrive\שולחן העבודה\crunch-master\website\auth.py", line 28, in signup_post

    upload_result = uploader.upload(image)

    File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\cloudinary\uploader.py", line 46, in upload

    return call_cacheable_api("upload", params, file=file, **options)

    File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\cloudinary\uploader.py", line 341, in call_cacheable_api

    result = call_api(action, params, http_headers, return_error, unsigned, file, timeout, **options)

    File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\cloudinary\uploader.py", line 357, in call_api

    params = utils.sign_request(params, options)

    File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\cloudinary\utils.py", line 546, in sign_request

    raise ValueError("Must supply api_key")

    ValueError: Must supply api_key

**Comment by jakbin** [comment]
if you are uploading image file on sign up, you need to provide cloudinary credentials.
